### ISSUE TITLE
商家应用-淘宝小程序真机不显示文本

### ISSUE THREAD

**Issue by daiqiaojun** [galacean/engine#1111]
在开发者工具的模拟器中是文字正常显示的，安卓真机预览和真机调试不显示文字。
ios是可以显示的

问题机型及版本：
oasis engine version: 0.8.0-beta.31
安卓：安卓12
淘宝版本：10.17.0

**Comment by singlecoder** [comment]
预计 1 月份看看

**Comment by singlecoder** [comment]
问题已经定位，修复 [PR](https://github.com/galacean/engine/pull/1499)
