### ISSUE TITLE
MultiPass should consider add new pass before original pass

### ISSUE THREAD

**Issue by yangfengzzz** [galacean/engine#1135]
if I replace old pass by:
`Shader.create("occlusionShader", [occlusionShader, Shader.find("pbr").passes[0]]);`

The old material already have one renderState and add an empty renderState before that. MultiPass should consider add new pass before original pass which can provide method to switch renderState

**Comment by GuoLei1990** [comment]
`Mateial.renderStates` will be deprecate in the future
