### ISSUE TITLE
Support baseURL

### ISSUE THREAD

**Issue by gz65555** [galacean/engine#1152]
```typescript
const glTF = await engine.resourceManager.load<GLTFResource>({
  url: "/horse.gltf",
  type: AssetType.Prefab,
});
```
Use URL query cause the problem: 
![image](https://user-images.githubusercontent.com/6926263/199686445-5bed8f92-7cee-47ab-bcfe-512519884929.png)

**Comment by GuoLei1990** [comment]
The url should "horse.gltf", maybe not "/horse.gltf"

**Comment by GuoLei1990** [comment]
https://github.com/galacean/engine/pull/1424
