### ISSUE TITLE
oasis-engine package.json 模块调整建议

### ISSUE THREAD

**Issue by yj1438** [galacean/engine#1313]
oasis-engine package.json 模块调整建议。

目前是
```
"main": "dist/browser.min.js",
"module": "dist/module.js",
"browser": "dist/browser.min.js",
```
建议调整为
```
"main": "dist/browser.js",
"module": "dist/module.js",
```

像 webpack 默认 browser 优先级大于 module，本地引用使用 dist/browser.min.js 不方便调试，只提供 module 兼容和效果实际更好。
模块本身也没必要提供  min 版本，项目自行整体处理。
cdn 引用的情况调整后也无影响。

@husong-sudo

**Comment by gz65555** [comment]
min 版本是 umd 发 cdn 必须的，所以肯定要提供，package.json 里可以没有

**Comment by gz65555** [comment]
之后 browser 字段里提供非压缩版本即可？

**Comment by yj1438** [comment]
> 之后 browser 字段里提供非压缩版本即可？ @yj1438
编译后的产物非压缩版本调试还是不太清晰
或者是，umd 产物的 //# sourceMappingURL= 没有的问题修一下，现在 sourcemap 文件也实际没用上

> min 版本是 umd 发 cdn 必须的，所以肯定要提供，package.json 里可以没有
umd 产物是要保留供cdn发布和老module兜底，package.json 里的 "browser" 没必要存在

@gz65555

**Comment by GuoLei1990** [comment]
Done
