### ISSUE TITLE
WebGL2 获取深度图错误

### ISSUE THREAD

**Issue by yuufen** [galacean/engine#1379]
webgl1 正确

**Comment by zhuxudong** [comment]
it's not supported  to sample depthTexture filterable  in webgl2 : https://github.com/KhronosGroup/OpenGL-API/issues/84
you can set depthTexture as `depthTexture.filterMode = TextureFilterMode.Point`

**Comment by zhuxudong** [comment]
@GuoLei1990 give warning in engine?

**Comment by zhuxudong** [comment]
it's not a bug, please use correct filterMode in OpenGL
