### ISSUE TITLE
load 资产时，返回：对象是否是从缓存里拿的

### ISSUE THREAD

**Issue by yuufen** [galacean/engine#1439]
业务需求：如果是从缓存拿的，需要 clone 一份加载到场景里；如果不是从缓存拿的则不用处理

**Comment by singlecoder** [comment]
最好描述下具体想干嘛，现在的描述已经是技术方案了

**Comment by yuufen** [comment]
有一个需求，场景中已有一个模型，需要加载第二个模型，第二个模型是用户选择的，有小概率和第一个模型是同一个模型。

我目前的做法是不管是不是同一个模型，我都 load 然后 add 到场景里。这样遇到的问题就是如果是同一个模型，第一个模型会消失。

因为这个需求实际上比较复杂，我没法在代码里判断第二个模型和第一个模型是否是同一个模型。

所以我希望引擎在 load 模型时能告诉我这个模型之前是否加载过，如果加载过，我就需要 clone 一份再 add 到场景里。

或者 load 时可以指定一个参数：
- true：如果之前加载过，就 clone 一份 entity
- false：如果之前加载过，返回缓存里的对象

**Comment by gz65555** [comment]
> 因为这个需求实际上比较复杂，我没法在代码里判断第二个模型和第一个模型是否是同一个模型。

@yuufen 可以详细说一下，按我的理解，封装一下 load 方法就可以判断了

> 或者 load 时可以指定一个参数：
> 
> * true：如果之前加载过，就 clone 一份 entity
> * false：如果之前加载过，返回缓存里的对象

@GuoLei1990 可以看看这类需求，我觉得这个可以考虑下用某种方式去做？

**Comment by GuoLei1990** [comment]
- Loader will use cache if resource loaded, you can load and clone
- You can get from cache with PR:https://github.com/galacean/engine/pull/1461
