### ISSUE TITLE
TextRender在淘宝平台真机上不显示

### ISSUE THREAD

**Issue by SongBana** [galacean/engine#1455]
**Describe the bug**
TextRender在淘宝IDE模拟器上可以显示，在真机上显示不出来，也不报错

**Screenshots**
![image](https://user-images.githubusercontent.com/26177426/230535012-5a469b8e-cda1-404c-9e00-b279632d2d50.png)

 - OS:  Android
 - Browser  淘宝app
 - Version 最新版
 - oasis-engine 0.8.3
 

 // 添加文字
    const textEntity = root.createChild("text");
    textEntity.transform.setPosition(0, 1.5, 0);
    const textRenderer = textEntity.addComponent(TextRenderer);
    textRenderer.fontSize = 30;
    textRenderer.text = "点击方块会弹出 toast !";

**Comment by SongBana** [comment]
> 1、IOS 是否有这个问题 2、麻烦提供下可复现的 DEMO

demo地址：https://github.com/SongBana/toasis
淘宝IDE：https://developer.taobao.com/?spm=a219a.15212435.0.0.61a3669aW0JW9L

**Comment by singlecoder** [comment]
> > 1、IOS 是否有这个问题 2、麻烦提供下可复现的 DEMO
> 
> demo地址：https://github.com/SongBana/toasis 淘宝IDE：https://developer.taobao.com/?spm=a219a.15212435.0.0.61a3669aW0JW9L

关联应用能否一起提供一下

**Comment by SongBana** [comment]
> > > 1、IOS 是否有这个问题 2、麻烦提供下可复现的 DEMO
> > 
> > 
> > demo地址：https://github.com/SongBana/toasis 淘宝IDE：https://developer.taobao.com/?spm=a219a.15212435.0.0.61a3669aW0JW9L
> 
> 关联应用能否一起提供一下

应用是随便找了一个，可以提供一下淘宝账号，我给你加下权限

**Comment by singlecoder** [comment]
> > > 1、IOS 是否有这个问题 2、麻烦提供下可复现的 DEMO
> > 
> > 
> > demo地址：https://github.com/SongBana/toasis 淘宝IDE：https://developer.taobao.com/?spm=a219a.15212435.0.0.61a3669aW0JW9L
> 
> 关联应用能否一起提供一下

**Comment by singlecoder** [comment]
> 

哈哈 不需要了，我自己搞了一个

**Comment by singlecoder** [comment]
问题已经定位，修复 PR https://github.com/galacean/engine/pull/1499，稍后我们会发一个 0.8 版本的包修复该问题

**Comment by singlecoder** [comment]
不过如果项目还没开始，建议直接使用 0.9 版本，我们  0.9 开始后正式改名为 Galacean
