### ISSUE TITLE
@galacean/xxx umd 产物全局变量名调整

### ISSUE THREAD

**Issue by yj1438** [galacean/engine#1458]
刚发布的 0.9.0-beta.80 和 1.0.0-alpha.6，umd 产物挂在 window(global) 下的全局变量名直接用的是包名：

* @galacean/engine-physics-lite: window['@galacean/engine-physics-lite']
* @galacean/engine: window['@galacean/engine']
* ...

对直接使用 cdn 引用的项目不太便利，一般 UMD 全局变量名也不用这种形式的名称。

建议 IIFE/UMD 全局变量名调整下：

* @galacean/engine:  GalaceanEngine
* @galacean/engine-physics-lite:  GalaceanEngine.PhysicsLite
* @galacean/engine-physics-physx:  GalaceanEngine.PhysicsPhysx

基本规则：
@galacean/engine 核心引擎全局变量 GalaceanEngine；
@galacean/engine-physics-lite、@galacean/engine-spine 等插件 @galacean/engine-aaa-bbb => GalaceanEngine.AaaBbb；

@GuoLei1990 @husong-sudo

**Comment by gz65555** [comment]
目前思路，在需要打包的 umd 的 repo 里的 package.json 里添加 umd 配置:

galacean-engine 里：
```json
{
  "umd": {
    "name": "Galacean"
  },
}
```
physics-physx 里：
```json
{
  "umd": {
    "name": "Galacean.PhysicsX",
    "globals": {
      "@galacean/engine": "Galacean"
    }
  }
}
```
配置了 globals 的 key 会作为 external 的 库，value 作为引用库的 global name。

二方库统一使用 Galacean 的 namespace
