### ISSUE TITLE
加载文件时不能识别大写的后缀

### ISSUE THREAD

**Issue by yuufen** [galacean/engine#1527]
加载文件时不能识别大写的后缀

![image](https://user-images.githubusercontent.com/44254340/235432323-027f2cef-7066-490a-aef6-ad91848f0619.png)

**Comment by FlyingDreamSky** [comment]
类似这种的也无法加载http://ip:port/getCorsFile?urlPath=aHR0cDovLzE5Mi4xNjguMTk5LjIxOToxOTgwMi9hcGkvc3lzdGVtL3N5cy9zeXN0ZW0vYXR0YWNobWVudC9nZXQ%2FaWQ9MTY2NDA5Mzk5NDc4MDQ2MzEwNSZydD0xNjg1NTg2NTE2NzM2JnNpZ249OGIzNzg0OGY5OTgyNmY2YjVhZDAzM2I0YmEwNWFjYTImZD0xJnRva2VuPUxlSzFPWEx6TFNwTXYzWVlSRllLJTJGTmpsY3F2Yk16alA4SGM3bFo4aEIlMkJ1UjN1YUdFZWlIVDVwTGFuT0hSUzhWN0dlVnM5OU5FSUZFSWk4UmJkb2hSdTZWSlAlMkJvMDYlMkJCblJxcE9QakFva2lXZ2lRV2twR2plR3FKNFJmOUQwYjZwOXJWbHNFOUV5OW1sTkFMd3BQcHQ2aWZzeFJuU1A1YlJZbWNNUk16YTFNJTNEJmZ1bGxmaWxlbmFtZT0yMDIyMTAwOTE1MTMwN19wYXJlbnRfZGlyZWN0b3J5XyVFNSU4QSU5RSVFNSU4NSVBQyVFNiVBNSVCQzA2LmdsdGY%3D&fullfilename=/20221009151307_parent_directory_%E5%8A%9E%E5%85%AC%E6%A5%BC06.gltf

**Comment by FlyingDreamSky** [comment]
找了下，可以传入一个LoadItem，指定type，但是url从?被截取了，求解

**Comment by zhuxudong** [comment]
> 找了下，可以传入一个LoadItem，指定type，但是url从?被截取了，求解

你这个链接是请求后端返回的，？后面的都是前端无法识别的
