### ISSUE TITLE
右键不能拖动了，会出现弹窗

### ISSUE THREAD

**Issue by Komorebi94** [galacean/engine#1542]
**Describe the bug**
![image](https://github.com/galacean/engine/assets/23524965/b6bd3be1-f04e-4033-a778-eb1ae7c9ab20)

在0.8.3的版本中，右键可以自用拖动模型，升级版本之后，右键拖动会出现默认事件

**Expected behavior**
希望右键可以自由拖动

**Comment by cptbtptpbcptdtptp** [comment]
之前的引擎是默认阻止了浏览器的右键菜单，但是在新版本中，我们将决定权交给了开发者，如果你不希望默认菜单被触发，只需要声明：
