### ISSUE TITLE
模型加载显示问题

### ISSUE THREAD

**Issue by yiiiiiiqianyao** [galacean/engine#1543]
![image](https://github.com/galacean/engine/assets/42212176/8bc8a5da-a817-4aaf-9c6b-c71d1c256883)

模型文件
https://mdn.alipayobjects.com/huamei_cwajh0/afts/file/A*MH7tQZ9YtjMAAAAAAAAAAAAADn19AQ/ANI_Mecha_run.glb

**Comment by zhuxudong** [comment]
it's not a bug, have fixed when blend mode set correct
