### ISSUE TITLE
Destroy a Material 

### ISSUE THREAD

**Issue by gz65555** [galacean/engine#1626]
**To Reproduce**
1. call `MeshRenderer.setMaterial`
2. Destroy the material of meshRenderer
3. call `MeshRenderer.setMaterial`
4. see error

**Screenshots**
![image](https://github.com/galacean/engine/assets/6926263/2cb5a13b-0c47-43c1-94fe-e7a24928db6f)

**Desktop (please complete the following information):**
 - Version 1.0.0-beta.12

**Additional context**
![image](https://github.com/galacean/engine/assets/6926263/70c733d6-fda3-4a7f-ab3c-43d043429dab)
internalMaterial has been destroyed. should not call `_addReferCount`

**Comment by GuoLei1990** [comment]
Done
