### ISSUE TITLE
请问 福气乐园和五福欢乐套圈圈 的界面元素是如何制作的哈

### ISSUE THREAD

**Issue by exment** [galacean/engine#1709]
您好 ，最近仔细阅读了 福气乐园和五福欢乐套圈圈 两款游戏的制作流程
请问这两款游戏的gui界面是怎么制作的哈，是直接用html不？
<img width="644" alt="image" src="https://github.com/galacean/engine/assets/29449778/23f6fe27-d5a4-4577-8c3b-79769fcc1a04">

**Comment by singlecoder** [comment]
你好，你标红的部分，乐园里除了左下角的角色控制遥感，其他是 DOM 层实现的，角色控制遥感是通过引擎提供的 2D 能力实现的。另外，引擎 GUI 我们也在规划中了，等我们的 GUI 系统上了，这些元素就可以直接一套搞定了

**Comment by exment** [comment]
请问gui系统什么时候上呢,一直关注中,从1.0一直推迟到了貌似1.3
然后gui是纯代码实现还是编辑器中实现哈

**Comment by singlecoder** [comment]
> 

1、GUI 系统目前进展是完成了初步的调研，顺利的话 1.2 会先上一部分，慢的话要到 1.3
2、GUI 先是引擎层实现，然后接入编辑器
3、DOM 层做一些简单 UI 也可以，但是要和 3D 进行嵌套就不行了，然后这种会通过事件来进行通信，可以看看我们之前发布的一些业务实战文章，也可以看看这里：https://galacean.antgroup.com/#/docs/latest/cn/editor-script-communication

**Comment by exment** [comment]
非常感谢！
