### ISSUE TITLE
TextRenderer bug

### ISSUE THREAD

**Issue by 1085069832** [galacean/engine#1775]
TextRenderer enableWrapping = true，不设置text或设置为空字符串报错
![20230919-162035](https://github.com/galacean/engine/assets/26847324/37de719e-6f48-48a1-84ab-cfe557c8e790)

**Comment by cptbtptpbcptdtptp** [comment]
麻烦提供一下对应引擎的版本号。

**Comment by 1085069832** [comment]
0.9.20



发自我的iPhone


------------------ Original ------------------
From: AZhan ***@***.***&gt;
Date: Tue,Sep 19,2023 4:29 PM
To: galacean/engine ***@***.***&gt;
Cc: 1085069832 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [galacean/engine] TextRenderer bug (Issue #1775)





 
麻烦提供一下对应引擎的版本号。

**Comment by singlecoder** [comment]
Has fixed https://github.com/galacean/engine/pull/1634
