### ISSUE TITLE
同时使用sprite 和 spine动画 报错 “Shader property renderer_SpriteTexture has been used as Material group.”

### ISSUE THREAD

**Issue by yichen454** [galacean/engine#1821]
**Describe the bug**
同时使用sprite 和 spine动画 报错
“Shader property renderer_SpriteTexture has been used as Material group.”
**To Reproduce**
  engine.resourceManager
    .load({
      urls: [
        "https://gw.alipayobjects.com/os/OasisHub/a66ef194-6bc8-4325-9a59-6ea9097225b1/1620888427489.json",
        "https://gw.alipayobjects.com/os/OasisHub/a1e3e67b-a783-4832-ba1b-37a95bd55291/1620888427490.atlas",
        "https://gw.alipayobjects.com/zos/OasisHub/a3ca8f62-1068-43a5-bb64-5c9a0f823dde/1620888427490.png"
      ],
      type: "spine"
    })
    .then((spineEntity: Entity) => {
      spineEntity.transform.setPosition(0, -15, 0);
      rootEntity.addChild(spineEntity);
      const spineAnimation = spineEntity.getComponent(SpineAnimation);
      spineAnimation.state.setAnimation(0, "walk", true);
      spineAnimation.scale = 0.05;
    });

  engine.resourceManager
  .load({
    url:
      "https://gw.alipayobjects.com/zos/OasisHub/a3ca8f62-1068-43a5-bb64-5c9a0f823dde/1620888427490.png",
      type: AssetType.Texture2D,
  })
  .then((texture: Texture2D) => {
    const spEntity = rootEntity.createChild('sp');
    const spriteRenderer = spEntity.addComponent(SpriteRenderer);
    const sprite = new Sprite(engine, texture);
    spriteRenderer.sprite = sprite;
  });

**Expected behavior**
Shader property renderer_SpriteTexture has been used as Material group.

**Comment by singlecoder** [comment]
引擎和Spine版本麻烦提供下哈

**Comment by yichen454** [comment]
"@galacean/engine": "1.1.0-beta.9",
"@galacean/engine-spine": "1.0.0-beta.0",

就是直接在示例里修改的https://codesandbox.io/s/6qmng4

**Comment by singlecoder** [comment]
spine 使用这个版本：1.0.0-beta.1，已经修复这个问题
