### ISSUE TITLE
Mobile Debug View in Code Editor Error

### ISSUE THREAD

**Issue by Oskang09** [galacean/engine#2134]
**Describe the bug**

Was playing around and having issues on second project, as per left side code-editor mobile debug view not working but run on seperated tabs was fine.

Project Link: https://galacean.antgroup.com/editor/project/46500008

**Screenshots**

![image](https://github.com/galacean/engine/assets/15674107/0e9d0694-e919-4ec7-b667-b343b934acdc)

**Desktop:**
 - OS: Windows
 - Browser: Chrome
 - Version: 125.0.6422.176 (Official Build) (64-bit)
 - Galacean Version: 1.2.0-beta.4
 
 **Error from Logs:**
 
 ```
 preview.js:1352 
 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at euL._getAssetVirtualPath (preview.js:1352:6404)
    at euL._buildIR (preview.js:1352:4792)
    at async preview.js:1352:7235
    at async euL.buildPackage (preview.js:1352:2626)
    at async eu0.prebuild (preview.js:1548:6389)
    at async m (preview.js:1552:1685)
    at async preview.js:1552:1972
 ```
 
 Suspected was because of this, but not sure why the new projects not created together by default, but first project was come with all these shaders, mesh and material
 
 **Note: image was taken from other working projects**
 
![image](https://github.com/galacean/engine/assets/15674107/22c2578e-ed52-4c4f-8a6a-85ae9516c94b)

**Comment by MrKou47** [comment]
Hi @Oskang09,Thanks for your issue. It seems like a bug in Galacean editor and we have fixed it recently. Could you try it again?

**Comment by Oskang09** [comment]
Hi @MrKou47 , yea it's working fine right now, Since issue was fixed so will close the issue.
