### ISSUE TITLE
Feature Request: Support upload audio file formats

### ISSUE THREAD

**Issue by Oskang09** [galacean/engine#2135]
**Is your feature request related to a problem? Please describe.**
For working on the soundtrack like background music or some sound effects it's easier to pre-defined and upload to the assets folder and we able to use it via the existing HTML5 Audio, now need always add in after export from the editor

**Describe the solution you'd like**
Allow to upload audio file formats like webm, mp3, mpeg, ogg

**Additional context**

For existing was using this way, so quite trouble for those we adding sound.

![image](https://github.com/galacean/engine/assets/15674107/df87a863-24ab-4c7e-a0e2-7f9a783c271e)

**Comment by JujieX** [comment]
Hi Oskang09!
Thank you for choosing our engine for game development! We do have a plan to support audio, it's now in the pr #1587, which includes a audio file loader that supports webm ogg mp3 format and ability for playing background music. It's most likely to be reviewed and added to the engine in July with 1.3 version release. And we will add this feature to the online editor shortly afterwards. Hope this info will help!

**Comment by Oskang09** [comment]
Hi JuJieX,

Wow good to know that, can't wait for the updates! Appreciate it. Since there's the PR so will just close this reqeust.
