### ISSUE TITLE
Changes doesn't trigger reload automatically

### ISSUE THREAD

**Issue by Oskang09** [galacean/engine#2151]
**Describe the bug**
Create new project and code changes or editor changes after saved won't trigger the reload automatically, will required to refresh page in order to have latest changes, as image the mobile debug view in code editor doesn't reload the page so it remains to previous version code until refresh the page.

Project Link: https://galacean.antgroup.com/editor/project/47100004

**Expected behavior**
When code save or editor save should reflect and reload automatically on mobile debug view, tab debug view.

**Screenshots**

![image](https://github.com/galacean/engine/assets/15674107/1e34fbb0-07f1-4b02-8db9-fee79a976dc5)

**Screenshots ( After refresh )**
![image](https://github.com/galacean/engine/assets/15674107/22dae4f1-2c15-4fb7-8f15-95abbb109ecf)

**Desktop:**

- OS: Windows
- Browser: Chrome
- Version: 125.0.6422.176 (Official Build) (64-bit)
- Galacean Version: 1.2.0-beta.4

**Comment by MrKou47** [comment]
It's a bug in the recently released version, and we have fixed it in the latest editor version. Could you check it again?

**Comment by Oskang09** [comment]
Hi @MrKou47 , tested was working right now, thanks lot for that. Since fixed will close for the issues.
