### ISSUE TITLE
Destroying ParticleRenderer leads to TypeError: Cannot read property '_isTemplate' of null

### ISSUE THREAD

**Issue by jtabibito** [galacean/engine#2161]
**Describe the bug**
Destroying ParticleRenderer leads to TypeError: Cannot read property '_isTemplate' of null，becase the entity had been set null before.

**To Reproduce**
`

    const scene = engine.sceneManager.activeScene;
    const renderer1 = scene.createRootEntity("Renderer").addComponent(ParticleRenderer);
    const mesh = new ModelMesh(engine, "mesh");
    renderer1.mesh = mesh;
    renderer1.destroy();

`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GuoLei1990** [comment]
FIxed in: https://github.com/galacean/engine/pull/2285
