### ISSUE TITLE
Blender导出时勾选了压缩的glb格式无法正常加载

### ISSUE THREAD

**Issue by MarukoKiun** [galacean/engine#2332]
1.1版本的时候是正常的，升级到1.3.6版本之后 在Blender中导出时勾选了压缩的glb格式无法正常加载，也不报错就是视图中什么都没出现。

使用官方示例https://galacean.antgroup.com/engine/examples/gltf-basic/ 将其中的模型路径换成任意压缩过的glb应该就能重现
或者使用官方的查看器https://galacean.antgroup.com/engine/gltf-viewer/ 也可以重现
模型的话 使用最简单的  Blender中的默认的Cube 就行了 只要是压缩的 就无法加载
[testLoadGlb.zip](https://github.com/user-attachments/files/16609365/testLoadGlb.zip)

**Comment by cptbtptpbcptdtptp** [comment]
你遇到的问题可能是 Draco 导致的，你可以通过如下方式验证：
- 在项目中打开 Logger 
```
Logger.enable();
```
- 再次运行有问题的项目，如果发现如下报错，那应该就是这个问题
```
GLTF parser has not supported required extension KHR_draco_mesh_compression.
```
你可以通过引入 Draco 解决，详情参考：https://github.com/galacean/engine-toolkit/tree/main/packages/draco

**Comment by MarukoKiun** [comment]
谢谢 现在可以了 ~
不过@galacean/engine-toolkit-draco这个包的package.json里面的引用路径错了哦  应该是 "module": "dist/es/index.js"诶

**Comment by cptbtptpbcptdtptp** [comment]
> 谢谢 现在可以了 ~ 不过@galacean/engine-toolkit-draco这个包的package.json里面的引用路径错了哦 应该是 "module": "dist/es/index.js"诶

OK 我们修复下。
