### ISSUE TITLE
关于UI组件的动效问题

### ISSUE THREAD

**Issue by exment** [galacean/engine#2367]
马上1.4版本要上UI组件
如果想在UI组件上实现复杂的效果，比如类似武器合成发光，嵌入3D内容，有什么规划不？
另外 galacean effect制作的内容能直接用不？

**Comment by cptbtptpbcptdtptp** [comment]
UI 组件也会支持自定义 Shader ，嵌入 3D 内容一般是通过将 3D 内容渲染至 RT ，再由 UI 展示 RT 实现的，这部分也在实现中。
galacean effect 制作的内容是可以在 Galacean 中展示的，依赖 @galacean/engine-mars 组件，具体的使用规则可以参考：
https://www.npmjs.com/package/@galacean/engine-mars

**Comment by exment** [comment]
非常感谢！
