### ISSUE TITLE
GLTF加载报错

### ISSUE THREAD

**Issue by 625673575** [galacean/engine#2453]
模型是从Unity里导出的，从其他的Web渲染器都能加载，babylon，filament，threejs，在galacean里报错了
[Uploading UnityChanSSU.zip…]()

**Comment by cptbtptpbcptdtptp** [comment]
添加一下报错详情或者上传模型，看起来模型没上传成功
![image](https://github.com/user-attachments/assets/3c24fcdd-48fd-4cef-9ff5-e9d84ebcfa89)

**Comment by 625673575** [comment]
[UnityChanSSU.zip](https://github.com/user-attachments/files/18033550/UnityChanSSU.zip)
OK，传好了

**Comment by cptbtptpbcptdtptp** [comment]
> [UnityChanSSU.zip](https://github.com/user-attachments/files/18033550/UnityChanSSU.zip) OK，传好了

确认一下，是拖拽到编辑器中无法加载成功对吗？

**Comment by cptbtptpbcptdtptp** [comment]
> [UnityChanSSU.zip](https://github.com/user-attachments/files/18033550/UnityChanSSU.zip) OK，传好了

我们检查了一下，发现是编辑器使用的 glTF 官方依赖 [@gltf-transform](https://www.npmjs.com/package/@gltf-transform/core) 触发的问题，我们将在近期将他的版本从 3.10.0 升级至 4.1.0 版本来规避这个问题，但是版本升级需要经过内部测试，所以需要等到下周发布。
此外，这个问题只会在编辑器中触发，如果在 Runtime 中加载 glTF 模型，是不会触发这个问题的。

**Comment by 625673575** [comment]
> > [UnityChanSSU.zip](https://github.com/user-attachments/files/18033550/UnityChanSSU.zip) OK，传好了
> 
> 确认一下，是拖拽到编辑器中无法加载成功对吗？

galacean runtime也是无法成功的，版本是1.3.22

**Comment by 625673575** [comment]
更新了版本可以了，之前的是1.0.5版本
