### ISSUE TITLE
Shader Optimization

### ISSUE THREAD

**Issue by gz65555** [galacean/engine#484]
**Is your feature request related to a problem? Please describe.**
Material serialization need to optimize shader.
- [ ] Split PBR Shader code. Do not use macro to control whether to use metallic workflow or specular workflow.
- [ ] I need get *Uniform Name* and *Macro Name* from `Material` easily.

**Additional context**
It's important for material serialization, so it's high priority.

**Comment by zhuxudong** [comment]
done
