### ISSUE TITLE
renderqueue sort error

### ISSUE THREAD

**Issue by zhuxudong** [galacean/engine#498]
**Describe the bug**
`quicksort` is wrong when `compareFunc` returns 0, what can be happened when `camera.isOrthographic === true`

**To Reproduce**
because of `element._distanceForSort` returns the same value when `camera.isOrthographic === true`, the renderqueue is out of order .

**Expected behavior**
`quickSort` should be stable when `compareFunc` returns 0

**Comment by singlecoder** [comment]
I had fix this bug, you can see https://github.com/oasis-engine/engine/pull/247

**Comment by zhuxudong** [comment]
> I had fix this bug, you can see #247

why is not merged?
