### ISSUE TITLE
gltf导入功能优化&&支持.ktx2文件格式

### ISSUE THREAD

**Issue by chenxuyaoniming** [galacean/engine#839]
1. 目前在源码内可以看到在导入gltf/glb模型过程中，对于贴图的加载，默认使用的是texture2D类型，不支持修改，这里是否能增加一个api，使用户可以根据自身情况，灵活调整加载资源的类型，例如将texture2D类型调整为引擎内已经实现的.ktx文件类型。

2. 目前.ktx2文件格式在threejs和babylonjs内已经得到了很好的支持，希望oasis能尽快跟进。😁

**Comment by GuoLei1990** [comment]
Done in PR https://github.com/galacean/engine/pull/1662
